### ISSUE TITLE
breaking changes in dplyr/tibble

### ISSUE THREAD

**Issue by stephenturner** [bioconnector/workshops#2]
[dplyr 0.5](https://github.com/hadley/dplyr/releases/tag/v0.5.0) and [tibble 1.1](https://github.com/hadley/tibble/releases/tag/v1.1) introduce some breaking changes. things that come to mind are 
- no arranging within groups, 
- tibble functions being split out / not exported from dplyr which may require loading separately, 
- warnings about future deprecation of summarize_each, mutate_each?
- they're now called "tibbles" not "table underscore DFs" or whatever we called them before. Change the narrative?

perhaps @vpnagraj could help test this one and suggest changes

**Comment by vpnagraj** [comment]
haven't used tibble or dplyr 0.5 yet but i'll take a look ... and will be sure to review the contributing.md before pushing any changes

**Comment by stephenturner** [comment]
some nice stuff in 0.5, FWIW.

re CONTRIBUTING - looks like a lot but isn't really. Rmd websites really simplifies things IMHO. Allows nice separation of source files in root and all build/deployed files in _site.

**Comment by stephenturner** [comment]
i think this is mostly fixed, especially now since we're not committing `site/`. see also #16 . @vpnagraj - double check that you're not doing any arrange within groups and `{summarize/mutate}_each`, reopen if necessary.
