### ISSUE TITLE
bims8382 2017

### ISSUE THREAD

**Issue by stephenturner** [bioconnector/workshops#28]
[BIMS8382 class 2016](http://bioconnector.github.io/bims8382/) was made by using a Makefile to render all Rmd files to HTML, and committing all files to both master and gh-pages ([source](https://github.com/bioconnector/bims8382). Using RMarkdown websites has been much easier to maintain here, and cleaner (only source files on master, only rendered files on gh-pages).

Rather than going back and updating bioconnector/bims8382, I'd like to use Rmarkdown website functionality for rendering the 2017 course materials. Instead of going back to bioconnector/bims8382 and updating everything, and maintaining two parallel repos, I propose we add bims8382-specific materials to _this_ repo. Do you agree, @vpnagraj ?

Some things to do (check them off here as you create separate issues):

- [x] add a syllabus (see http://bioconnector.org/bims8382/syllabus.html)
- [x] update the existing FAQ (see http://bioconnector.org/bims8382/faq.html)
- [x] add homework/assignments for all lessons from bioconnector/bims8382
- [x] update old bims8382's website's landing page bioconnector/bims8382#8 to link to this repo

**Comment by vpnagraj** [comment]
@stephenturner yeah i totally agree it would be much easier to maintain everything in one place ... that said i don't really have my head around how we would represent the bims8382-specific content (syllabus, homework, etc) on the /workshops site ... a few questions/issues i'm considering ...

- navigation: would bims8382 be a tab on the main menu? underneath the help section? 
- would the "topics" from the current bims8382 site link to corresponding workshop lessons?
- would the web address for the landing page (currently bioconnector.org/bims8382) now be bioconnector.org/workshops/bims8382 ?
- some of the [current workshop lessons include our homework](http://bioconnector.org/workshops/r-viz-gapminder.html#homework) from bims8382 

let me know what you think, in the meantime i'll work on my fork and contribute via PR

**Comment by stephenturner** [comment]
@vpnagraj 

> navigation: would bims8382 be a tab on the main menu? underneath the help section?

could do that. under that dropdown have the syllabus, course-specific faqs, etc.

> would the "topics" from the current bims8382 site link to corresponding workshop lessons?

We could just keep the current bims8382 repo/site as is. Or else rename it bims8382-2016, and set the bims8382 site to HTML redirect to the syllabus on the current workshops page. You can do this all on github. E.g., just going to the top-level .org site redirects you to workshops https://github.com/bioconnector/bioconnector.github.io/blob/master/index.html

> would the web address for the landing page (currently bioconnector.org/bims8382) now be bioconnector.org/workshops/bims8382 ?

Not sure how to implement this with RMD websites, so probably not. I really just want to re-use all the existing material as much as possible. 

I always had bioconnector.org redirect to bioconnector.org/workshops, thinking that we might want to put something else under the top level .org site. We could move everything up to the top level .org site and redirect workshops there. That way it wouldn't look like the BIMS class was simply reusing the workshops website. I don't think this would break anything.

> some of the current workshop lessons include our homework from bims8382

Great. Less work. We could just roll all the homework right into their corresponding lesson. Or not. I don't care either way. You have a preference?

**Comment by stephenturner** [comment]
closed via 8e34831efb68ff7f6221d8945302e794f3aea9e7 in bioconnector/workshops#8
