### ISSUE TITLE
interactive viz: hc_add_series_scatter deprecated 

### ISSUE THREAD

**Issue by stephenturner** [bioconnector/workshops#40]
Some warnings on building the interactive viz lesson:

```
Warning messages:
1: 'hc_add_series_scatter' is deprecated.
Use 'hc_add_series' instead.
See help("Deprecated")
2: 'hc_add_series_scatter' is deprecated.
Use 'hc_add_series' instead.
See help("Deprecated")
```

@vpnagraj

**Comment by stephenturner** [comment]
I'm getting close with `hc_add_series()` but the labels aren't showing up. Not sure how to fix. 

I.e., instead of

```r
highchart() %>%
    hc_add_series_scatter(x = kubrick$year, y = kubrick$rating, z = kubrick$budget, label = kubrick$title)
```

```r
 highchart() %>%
    hc_add_series(data=kubrick, hcaes(x = year, y = rating, z = budget, label=title), type="scatter")
```

mostly works, but no labels. @vpnagraj

**Comment by vpnagraj** [comment]
@stephenturner sorry i started digging into this back in march and pretty sure i got to same place you did ...  will investigate again may have to just change that example 👎 

teaching this workshop again in a few weeks so i might even add another js package as an example ... if so, will try to resolve this with that PR

**Comment by vpnagraj** [comment]
@stephenturner see [pr](https://github.com/bioconnector/workshops/pull/45)

**Comment by stephenturner** [comment]
fixed in https://github.com/bioconnector/workshops/commit/e7bf94aca181f1e7131c5cb631145b6466add386
