### ISSUE TITLE
ncbi lesson: `entrez_fetch` fasta sequence causes build failure

### ISSUE THREAD

**Issue by stephenturner** [bioconnector/workshops#43]
Line [216 in the ncbi lesson](https://github.com/bioconnector/workshops/blame/10221465d1b7bb4974424b1ff108aa4af20238f0/r-ncbi.Rmd#L216) fails...

```r
entrez_fetch(db = "nuccore", id = nuclinkid, rettype = "fasta")
```

...with the error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
```

This results in a build error. In 10221465d1b7bb4974424b1ff108aa4af20238f0 I turned off (`eval=FALSE`) a few chunks that create or refer to this data.

@vpnagraj

**Comment by vpnagraj** [comment]
@stephenturner just seeing that myself now ... will modify the lesson

**Comment by vpnagraj** [comment]
@stephenturner see [pr](https://github.com/bioconnector/workshops/pull/45)

**Comment by stephenturner** [comment]
fixed in https://github.com/bioconnector/workshops/commit/e7bf94aca181f1e7131c5cb631145b6466add386
